Vagrant.configure("2") do |config|



# General Vagrant VM configuration
config.vm.box = "ubuntu/bionic64"



config.vm.define "db-server" do |db|
db.vm.network :forwarded_port, guest: 3306, host: 3306
db.vm.network :forwarded_port, guest: 80, host: 3306
db.vm.provision "shell", path: "bootstrap.sh"
end



# Adjustment for VM
config.vm.provider :virtualbox do |vb|
vb.customize [
'modifyvm', :id,
'--natdnshostresolver1', 'on',
'--memory', '1024',
'--cpus', '4'
]
end



end